import { ChordFunction } from "./chord-function";
import { Step } from "./interval";
import { Mode } from "./mode";
import { Triad } from "./triad";

export const SCALES: Record<Mode, Record<ChordFunction, Triad>> = {
  [Mode.IONIAN]: {
    [ChordFunction.I]: Triad.MAJOR,
    [ChordFunction.II]: Triad.MINOR,
    [ChordFunction.III]: Triad.MINOR,
    [ChordFunction.IV]: Triad.MAJOR,
    [ChordFunction.V]: Triad.MAJOR,
    [ChordFunction.VI]: Triad.MINOR,
    [ChordFunction.VII]: Triad.DIMINISHED,
  },
  [Mode.DORIAN]: {
    [ChordFunction.I]: Triad.MINOR,
    [ChordFunction.II]: Triad.MINOR,
    [ChordFunction.III]: Triad.MAJOR,
    [ChordFunction.IV]: Triad.MAJOR,
    [ChordFunction.V]: Triad.MINOR,
    [ChordFunction.VI]: Triad.DIMINISHED,
    [ChordFunction.VII]: Triad.MAJOR,
  },
  [Mode.PHRYGIAN]: {
    [ChordFunction.I]: Triad.MINOR,
    [ChordFunction.II]: Triad.MAJOR,
    [ChordFunction.III]: Triad.MAJOR,
    [ChordFunction.IV]: Triad.MINOR,
    [ChordFunction.V]: Triad.DIMINISHED,
    [ChordFunction.VI]: Triad.MAJOR,
    [ChordFunction.VII]: Triad.MINOR,
  },
  [Mode.LYDIAN]: {
    [ChordFunction.I]: Triad.MAJOR,
    [ChordFunction.II]: Triad.MAJOR,
    [ChordFunction.III]: Triad.MINOR,
    [ChordFunction.IV]: Triad.DIMINISHED,
    [ChordFunction.V]: Triad.MAJOR,
    [ChordFunction.VI]: Triad.MINOR,
    [ChordFunction.VII]: Triad.MINOR,
  },
  [Mode.MIXOLYDIAN]: {
    [ChordFunction.I]: Triad.MAJOR,
    [ChordFunction.II]: Triad.MINOR,
    [ChordFunction.III]: Triad.DIMINISHED,
    [ChordFunction.IV]: Triad.MAJOR,
    [ChordFunction.V]: Triad.MINOR,
    [ChordFunction.VI]: Triad.MINOR,
    [ChordFunction.VII]: Triad.MAJOR,
  },
  [Mode.AEOLIAN]: {
    [ChordFunction.I]: Triad.MINOR,
    [ChordFunction.II]: Triad.DIMINISHED,
    [ChordFunction.III]: Triad.MAJOR,
    [ChordFunction.IV]: Triad.MINOR,
    [ChordFunction.V]: Triad.MINOR,
    [ChordFunction.VI]: Triad.MAJOR,
    [ChordFunction.VII]: Triad.MAJOR,
  },
  [Mode.LOCRIAN]: {
    [ChordFunction.I]: Triad.DIMINISHED,
    [ChordFunction.II]: Triad.MAJOR,
    [ChordFunction.III]: Triad.MINOR,
    [ChordFunction.IV]: Triad.MINOR,
    [ChordFunction.V]: Triad.MAJOR,
    [ChordFunction.VI]: Triad.MAJOR,
    [ChordFunction.VII]: Triad.MINOR,
  },
};

export const SCALE_INTERVALS = {
  [Mode.IONIAN]: [
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
  ],
  [Mode.DORIAN]: [
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
  ],
  [Mode.PHRYGIAN]: [
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
  ],
  [Mode.LYDIAN]: [
    Step.WHOLE,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
  ],
  [Mode.MIXOLYDIAN]: [
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
  ],
  [Mode.AEOLIAN]: [
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
  ],
  [Mode.LOCRIAN]: [
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.HALF,
    Step.WHOLE,
    Step.WHOLE,
    Step.WHOLE,
  ],
};
