import { Accidental } from "./accidental";
import { Note } from "./note";

export enum TwentyOneNote {
  C_NATURAL = 0,
  C_SHARP = 1,
  C_FLAT = 2,
  D_NATURAL = 3,
  D_SHARP = 4,
  D_FLAT = 5,
  E_NATURAL = 6,
  E_SHARP = 7,
  E_FLAT = 8,
  F_NATURAL = 9,
  F_SHARP = 10,
  F_FLAT = 11,
  G_NATURAL = 12,
  G_SHARP = 13,
  G_FLAT = 14,
  A_NATURAL = 15,
  A_SHARP = 16,
  A_FLAT = 17,
  B_NATURAL = 18,
  B_SHARP = 19,
  B_FLAT = 20,
}

export const TWENTY_ONE_NOTES = {
  [TwentyOneNote.C_NATURAL]: { note: Note.C, accidental: Accidental.NATURAL },
  [TwentyOneNote.C_SHARP]: { note: Note.C, accidental: Accidental.SHARP },
  [TwentyOneNote.C_FLAT]: { note: Note.C, accidental: Accidental.FLAT },
  [TwentyOneNote.D_NATURAL]: { note: Note.D, accidental: Accidental.NATURAL },
  [TwentyOneNote.D_SHARP]: { note: Note.D, accidental: Accidental.SHARP },
  [TwentyOneNote.D_FLAT]: { note: Note.D, accidental: Accidental.FLAT },
  [TwentyOneNote.E_NATURAL]: { note: Note.E, accidental: Accidental.NATURAL },
  [TwentyOneNote.E_SHARP]: { note: Note.E, accidental: Accidental.SHARP },
  [TwentyOneNote.E_FLAT]: { note: Note.E, accidental: Accidental.FLAT },
  [TwentyOneNote.F_NATURAL]: { note: Note.F, accidental: Accidental.NATURAL },
  [TwentyOneNote.F_SHARP]: { note: Note.F, accidental: Accidental.SHARP },
  [TwentyOneNote.F_FLAT]: { note: Note.F, accidental: Accidental.FLAT },
  [TwentyOneNote.G_NATURAL]: { note: Note.G, accidental: Accidental.NATURAL },
  [TwentyOneNote.G_SHARP]: { note: Note.G, accidental: Accidental.SHARP },
  [TwentyOneNote.G_FLAT]: { note: Note.G, accidental: Accidental.FLAT },
  [TwentyOneNote.A_NATURAL]: { note: Note.A, accidental: Accidental.NATURAL },
  [TwentyOneNote.A_SHARP]: { note: Note.A, accidental: Accidental.SHARP },
  [TwentyOneNote.A_FLAT]: { note: Note.A, accidental: Accidental.FLAT },
  [TwentyOneNote.B_NATURAL]: { note: Note.B, accidental: Accidental.NATURAL },
  [TwentyOneNote.B_SHARP]: { note: Note.B, accidental: Accidental.SHARP },
  [TwentyOneNote.B_FLAT]: { note: Note.B, accidental: Accidental.FLAT },
};
